export enum Colors {
  PRIMARY_1 = 'primary-1',
  PRIMARY_2 = 'primary-2',
  PRIMARY_3 = 'primary-3',
  PRIMARY_4 = 'primary-4',
  PRIMARY_5 = 'primary-5',

  SECONDARY_1 = 'secondary-1',
  SECONDARY_2 = 'secondary-2',
  SECONDARY_3 = 'secondary-3',
  SECONDARY_4 = 'secondary-4',
  SECONDARY_5 = 'secondary-5',

  NEUTRAL_1 = 'neutral-1',
  NEUTRAL_15 = 'neutral-15',
  NEUTRAL_2 = 'neutral-2',
  NEUTRAL_25 = 'neutral-25',
  NEUTRAL_3 = 'neutral-3',
  NEUTRAL_35 = 'neutral-35',
  NEUTRAL_4 = 'neutral-4',
  NEUTRAL_45 = 'neutral-45',
  NEUTRAL_5 = 'neutral-5',
  NEUTRAL_55 = 'neutral-55',
  NEUTRAL_6 = 'neutral-6',
  NEUTRAL_65 = 'neutral-65',
  NEUTRAL_7 = 'neutral-7',
  NEUTRAL_75 = 'neutral-75',
  NEUTRAL_8 = 'neutral-8',
  NEUTRAL_85 = 'neutral-85',
  NEUTRAL_9 = 'neutral-9',
  NEUTRAL_95 = 'neutral-95',
  NEUTRAL_10 = 'neutral-10',
}
